package br.com.tecnomotor.marvin.utils.constant

object ParameterSharedPreferences {
    const val LINK_OPTION_DEFAULT = "LINK_OPTION_DEFAULT"
    const val LINK_OPTION_1 = "LINK_OPTION_1"
    const val LINK_OPTION_2 = "LINK_OPTION_2"
    const val SHARED_PREFERENCES_CONFIGURATION_SYNCHRONIZATION = "spConfigurationSynchronization"

    const val PARAMETER_TYPE_POINT_INJECTOR_TEST_MAX_XID = "parameterTypePointInjectorTestMaxXid"
    const val PARAMETER_BRAND_MAX_XID = "parameterBrandMaxXid"
    const val PARAMETER_INJECTOR_MAX_XID = "parameterInjectorMaxXid"
    const val PARAMETER_INJECTOR_PLATFORM_MAX_XID = "parameterInjectorPlatformMaxXid"
    const val PARAMETER_INJECTOR_PLATFORM_PLAN_TEST_MAX_XID = "parameterInjectorPlatformPlantTestMaxXid"
    const val PARAMETER_INJECTOR_PLAN_TEST_MAX_XID = "parameterInjectorPlanTestMaxXid"
    const val PARAMETER_PLATFORM_MAX_XID = "parameterPlatformMaxXid"
    const val PARAMETER_POINT_TEST_INJECTOR_MAX_XID = "parameterPointTestInjectorMaxXid"
    const val PARAMETER_REVISION_MAX_XID = "parameterRevisionMaxXid"
    const val PARAMETER_REVISION_INJECTOR_MAX_XID = "parameterRevisionInjectorMaxXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_TEST_INJECTOR_MAX_XID = "parameterTranslateTypePlantTestInjectorMaxXid"
    const val PARAMETER_TRANSLATE_TYPE_POINT_INJECTOR_MAX_XID = "parameterTranslateTypePointInjectorMaxXid"
    const val PARAMETER_TYPE_PLAN_TEST_MAX_XID = "parameterTypePlanTestMaxXid"
    const val PARAMETER_VERSION_MAX_XID = "parameterVersionMaxXid"

    const val PARAMETER_TYPE_POINT_INJECTOR_TEST_MAX_XID_TRY_AGAIN = "parameterTypePointInjectorTestMaxXidTryAgain"
    const val PARAMETER_BRAND_MAX_XID_TRY_AGAIN = "parameterBrandMaxXidTryAgain"
    const val PARAMETER_INJECTOR_MAX_XID_TRY_AGAIN = "parameterInjectorMaxXidTryAgain"
    const val PARAMETER_INJECTOR_PLATFORM_MAX_XID_TRY_AGAIN = "parameterInjectorPlatformMaxXidTryAgain"
    const val PARAMETER_INJECTOR_PLATFORM_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterInjectorPlatformPlantTestMaxXidTryAgain"
    const val PARAMETER_INJECTOR_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterInjectorPlanTestMaxXidTryAgain"
    const val PARAMETER_PLATFORM_MAX_XID_TRY_AGAIN = "parameterPlatformMaxXidTryAgain"
    const val PARAMETER_POINT_TEST_INJECTOR_MAX_XID_TRY_AGAIN = "parameterPointTestInjectorMaxXidTryAgain"
    const val PARAMETER_REVISION_MAX_XID_TRY_AGAIN = "parameterRevisionMaxXidTryAgain"
    const val PARAMETER_REVISION_INJECTOR_MAX_XID_TRY_AGAIN = "parameterRevisionInjectorMaxXidTryAgain"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_TEST_INJECTOR_MAX_XID_TRY_AGAIN = "parameterTranslateTypePlantTestInjectorMaxXidTryAgain"
    const val PARAMETER_TRANSLATE_TYPE_POINT_INJECTOR_MAX_XID_TRY_AGAIN = "parameterTranslateTypePointInjectorMaxXidTryAgain"
    const val PARAMETER_TYPE_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterTypePlanTestMaxXidTryAgain"
    const val PARAMETER_VERSION_MAX_XID_TRY_AGAIN = "parameterVersionMaxXidTryAgain"

    const val PARAMETER_LOGIN = "parameterLogin"
    const val PARAMETER_PASSWORD = "parameterPassword"

    const val PARAMETER_TYPE_POINT_INJECTOR_TEST_CURRENT_XID = "parameterTypePointInjectorTestCurrentXid"
    const val PARAMETER_BRAND_CURRENT_XID = "parameterBrandCurrentXid"
    const val PARAMETER_INJECTOR_CURRENT_XID = "parameterInjectorCurrentXid"
    const val PARAMETER_INJECTOR_PLATFORM_CURRENT_XID = "parameterInjectorPlatformCurrentXid"
    const val PARAMETER_INJECTOR_PLATFORM_PLAN_TEST_CURRENT_XID = "parameterInjectorPlatformPlantTestCurrentXid"
    const val PARAMETER_INJECTOR_PLAN_TEST_CURRENT_XID = "parameterInjectorPlanTestCurrentXid"
    const val PARAMETER_PLATFORM_CURRENT_XID = "parameterPlatformCurrentXid"
    const val PARAMETER_POINT_TEST_INJECTOR_CURRENT_XID = "parameterPointTestInjectorCurrentXid"
    const val PARAMETER_REVISION_CURRENT_XID = "parameterRevisionCurrentXid"
    const val PARAMETER_REVISION_INJECTOR_CURRENT_XID = "parameterRevisionInjectorCurrentXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_TEST_INJECTOR_CURRENT_XID = "parameterTranslateTypePlantTestInjectorCurrentXid"
    const val PARAMETER_TRANSLATE_TYPE_POINT_INJECTOR_CURRENT_XID = "parameterTranslateTypePointInjectorCurrentXid"
    const val PARAMETER_TYPE_PLAN_TEST_CURRENT_XID = "parameterTypePlanTestCurrentXid"
    const val PARAMETER_VERSION_CURRENT_XID = "parameterVersionCurrentXid"
    const val PARAMETER_TRANSLATE_TYPE_POINT_TEST_PUMP_MAX_XID = "parameterTranslateTypePointTestPumpMaxXid"

    //Constants modules pump
    const val PARAMETER_PUMP_MAX_XID = "parameterPumpMaxXid"
    const val PARAMETER_PUMP_PLATFORM_MAX_XID = "parameterPumpPlatformMaxXid"
    const val PARAMETER_PUMP_PLATFORM_PLAN_TEST_MAX_XID = "parameterPumpPlatformPlanTestMaxXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_PUMP_MAX_XID = "parameterTranslateTypePlanPumpMaxXid"
    const val PARAMETER_POINT_TEST_PUMP_MAX_XID = "parameterPointTestPumpMaxXid"
    const val PARAMETER_REVISION_PUMP_MAX_XID = "parameterRevisionPumpMaxXid"
    const val PARAMETER_REVISION_PUMP_PLAN_MAX_XID = "parameterRevisionPlanPumpMaxXid"
    const val PARAMETER_PUMP_PLAN_TEST_MAX_XID = "parameterPumpPlanTestMaxXid"
    const val PARAMETER_TYPE_PUMP_MAX_XID = "parameterTypePumpMaxXid"
    const val PARAMETER_TYPE_POINT_TEST_PUMP_MAX_XID = "parameterTypePointTestPumpMaxXid"

    const val PARAMETER_PUMP_MAX_XID_TRY_AGAIN = "parameterPumpMaxXidTryAgain"
    const val PARAMETER_PUMP_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterPumpPlanTestMaxXidTryAgain"
    const val PARAMETER_PUMP_PLATFORM_MAX_XID_TRY_AGAIN = "parameterPumpPlatformMaxXidTryAgain"
    const val PARAMETER_POINT_TEST_PUMP_MAX_XID_TRY_AGAIN = "parameterPointTestPumpMaxXidTryAgain"
    const val PARAMETER_PUMP_PLATFORM_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterPumpPlatformPlanTestMaxXidTryAgain"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_PUMP_MAX_XID_TRY_AGAIN = "parameterTranslateTypePlanPumpMaxXidTryAgain"
    const val PARAMETER_REVISION_PUMP_MAX_XID_TRY_AGAIN = "parameterRevisionPumpMaxXidTryAgain"
    const val PARAMETER_REVISION_PUMP_PLAN_MAX_XID_TRY_AGAIN = "parameterRevisionPlanPumpMaxXidTryAgain"
    const val PARAMETER_TRANSLATE_TYPE_POINT_TEST_PUMP_MAX_XID_TRY_AGAIN = "parameterTranslateTypePointTestPumpMaxXidTryAgain"
    const val PARAMETER_TYPE_PUMP_MAX_XID_TRY_AGAIN = "parameterTypePumpMaxXidTryAgain"
    const val PARAMETER_TYPE_POINT_TEST_PUMP_MAX_XID_TRY_AGAIN = "parameterTypePointTestPumpMaxXidTryAgain"
    const val PARAMETER_TYPE_POINT_PUMP_TEST_MAX_XID_TRY_AGAIN = "parameterTypePointPumpTestMaxXidTryAgain"

    const val PARAMETER_PUMP_CURRENT_XID = "parameterPumpCurrentXid"
    const val PARAMETER_PUMP_PLATFORM_CURRENT_XID = "parameterPumpPlatformCurrentXid"
    const val PARAMETER_PUMP_PLATFORM_PLAN_TEST_CURRENT_XID = "parameterPumpPlatformPlanTestCurrentXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_PUMP_CURRENT_XID = "parameterTranslateTypePlanPumpCurrentXid"
    const val PARAMETER_REVISION_PUMP_CURRENT_XID = "parameterRevisionPumpCurrentXid"
    const val PARAMETER_POINT_TEST_PUMP_CURRENT_XID = "parameterPointTestPumpCurrentXid"
    const val PARAMETER_PUMP_PLAN_TEST_CURRENT_XID = "parameterPumpPlanTestCurrentXid"
    const val PARAMETER_REVISION_PUMP_PLAN_CURRENT_XID = "parameterRevisionPlanPumpCurrentXid"
    const val PARAMETER_TRANSLATE_TYPE_POINT_TEST_PUMP_CURRENT_XID = "parameterTranslateTypePointTestPumpCurrentXid"
    const val PARAMETER_TYPE_PUMP_CURRENT_XID = "parameterTypePumpCurrentXid"
    const val PARAMETER_TYPE_POINT_TEST_PUMP_CURRENT_XID = "parameterTypePointTestPumpCurrentXid"


    //Constants modules sensor
    const val PARAMETER_SENSOR_MAX_XID = "parameterSensorMaxXid"
    const val PARAMETER_SENSOR_PLATFORM_MAX_XID = "parameterSensorPlatformMaxXid"
    const val PARAMETER_SENSOR_PLATFORM_PLAN_TEST_MAX_XID = "parameterSensorPlatformPlanTestMaxXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_SENSOR_MAX_XID = "parameterTranslateTypePlanSensorMaxXid"
    const val PARAMETER_REVISION_SENSOR_MAX_XID = "parameterRevisionSensorMaxXid"
    const val PARAMETER_REVISION_SENSOR_PLAN_MAX_XID = "parameterRevisionPlanSensorMaxXid"
    const val PARAMETER_SENSOR_PLAN_TEST_MAX_XID = "parameterSensorPlanTestMaxXid"

    const val PARAMETER_SENSOR_MAX_XID_TRY_AGAIN = "parameterSensorMaxXidTryAgain"
    const val PARAMETER_SENSOR_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterSensorPlanTestMaxXidTryAgain"
    const val PARAMETER_SENSOR_PLATFORM_MAX_XID_TRY_AGAIN = "parameterSensorPlatformMaxXidTryAgain"
    const val PARAMETER_SENSOR_PLATFORM_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterSensorPlatformPlanTestMaxXidTryAgain"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_SENSOR_MAX_XID_TRY_AGAIN = "parameterTranslateTypePlanSensorMaxXidTryAgain"
    const val PARAMETER_REVISION_SENSOR_MAX_XID_TRY_AGAIN = "parameterRevisionSensorMaxXidTryAgain"
    const val PARAMETER_REVISION_SENSOR_PLAN_MAX_XID_TRY_AGAIN = "parameterRevisionPlanSensorMaxXidTryAgain"
    const val PARAMETER_TYPE_SENSOR_MAX_XID_TRY_AGAIN = "parameterTypeSensorMaxXidTryAgain"

    const val PARAMETER_SENSOR_CURRENT_XID = "parameterSensorCurrentXid"
    const val PARAMETER_SENSOR_PLATFORM_CURRENT_XID = "parameterSensorPlatformCurrentXid"
    const val PARAMETER_SENSOR_PLATFORM_PLAN_TEST_CURRENT_XID = "parameterSensorPlatformPlanTestCurrentXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_SENSOR_CURRENT_XID = "parameterTranslateTypePlanSensorCurrentXid"
    const val PARAMETER_REVISION_SENSOR_CURRENT_XID = "parameterRevisionSensorCurrentXid"
    const val PARAMETER_SENSOR_PLAN_TEST_CURRENT_XID = "parameterSensorPlanTestCurrentXid"
    const val PARAMETER_REVISION_SENSOR_PLAN_CURRENT_XID = "parameterRevisionPlanSensorCurrentXid"

    //Constants modules valve
    const val PARAMETER_VALVE_MAX_XID = "parameterValveMaxXid"
    const val PARAMETER_VALVE_PLAN_TEST_MAX_XID = "parameterValvePlanTestMaxXid"
    const val PARAMETER_VALVE_PLATFORM_MAX_XID = "parameterValvePlatformMaxXid"
    const val PARAMETER_VALVE_PLATFORM_PLAN_MAX_XID = "parameterValvePlatformPlanTestMaxXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_VALVE_MAX_XID = "parameterTranslateTypePlanValveMaxXid"
    const val PARAMETER_REVISION_VALVE_MAX_XID = "parameterRevisionValveMaxXid"
    const val PARAMETER_REVISION_VALVE_PLAN_MAX_XID = "parameterRevisionPlanValveMaxXid"
    const val PARAMETER_VALVE_PLAN_MAX_XID = "parameterValvePlanMaxXid"

    const val PARAMETER_VALVE_MAX_XID_TRY_AGAIN = "parameterValveMaxXidTryAgain"
    const val PARAMETER_VALVE_PLAN_TEST_MAX_XID_TRY_AGAIN = "parameterValvePlanTestMaxXidTryAgain"
    const val PARAMETER_VALVE_PLATFORM_MAX_XID_TRY_AGAIN = "parameterValvePlatformMaxXidTryAgain"
    const val PARAMETER_VALVE_PLATFORM_PLAN_MAX_XID_TRY_AGAIN = "parameterValvePlatformPlanMaxXidTryAgain"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_VALVE_MAX_XID_TRY_AGAIN = "parameterTranslateTypePlanValveMaxXidTryAgain"
    const val PARAMETER_REVISION_VALVE_MAX_XID_TRY_AGAIN = "parameterRevisionValveMaxXidTryAgain"
    const val PARAMETER_REVISION_VALVE_PLAN_MAX_XID_TRY_AGAIN = "parameterRevisionPlanValveMaxXidTryAgain"
    const val PARAMETER_TYPE_VALVE_MAX_XID_TRY_AGAIN = "parameterTypeValveMaxXidTryAgain"

    const val PARAMETER_VALVE_CURRENT_XID = "parameterValveCurrentXid"
    const val PARAMETER_VALVE_PLATFORM_CURRENT_XID = "parameterValvePlatformCurrentXid"
    const val PARAMETER_VALVE_PLATFORM_PLAN_CURRENT_XID = "parameterValvePlatformPlanCurrentXid"
    const val PARAMETER_TRANSLATE_TYPE_PLAN_VALVE_CURRENT_XID = "parameterTranslateTypePlanValveCurrentXid"
    const val PARAMETER_REVISION_VALVE_CURRENT_XID = "parameterRevisionValveCurrentXid"
    const val PARAMETER_VALVE_PLAN_TEST_CURRENT_XID = "parameterValvePlanTestCurrentXid"
    const val PARAMETER_REVISION_VALVE_PLAN_CURRENT_XID = "parameterRevisionPlanValveCurrentXid"

    //Constants modules parameter remote
    const val PARAMETER_PARAMETER_REMOTE_MAX_XID = "parameterParameterRemoteMaxXid"
    const val PARAMETER_PERMISSION_PARAMETER_REMOTE_MAX_XID = "parameterPermissionParameterRemoteMaxXid"
    const val PARAMETER_TRANSLATE_PERMISSION_PARAMETER_REMOTE_MAX_XID = "parameterTranslatePermissionParameterRemoteMaxXid"


    const val PARAMETER_PARAMETER_REMOTE_MAX_XID_TRY_AGAIN = "parameterParameterRemoteMaxXidTryAgain"
    const val PARAMETER_PERMISSION_PARAMETER_REMOTE_MAX_XID_TRY_AGAIN = "parameterPermissionParameterRemoteMaxXidTryAgain"
    const val PARAMETER_TRANSLATE_PERMISSION_PARAMETER_REMOTE_MAX_XID_TRY_AGAIN = "parameterTranslatePermissionParameterRemoteMaxXidTryAgain"


    const val PARAMETER_PARAMETER_REMOTE_CURRENT_XID = "parameterParameterRemoteCurrentXid"
    const val PARAMETER_PERMISSION_PARAMETER_REMOTE_CURRENT_XID = "parameterPermissionParameterRemoteCurrentXid"
    const val PARAMETER_TRANSLATE_PERMISSION_PARAMETER_REMOTE_CURRENT_XID = "parameterTranslatePermissionParameterRemotePlanCurrentXid"

}